name: exifdart
version: 0.7.0+2
author: Peter Siroki <psiroki@users.noreply.github.com>
description: Decode Exif data from jpeg files (Dart port based on
  https://github.com/exif-js/exif-js/)
homepage: https://www.github.com/psiroki/exifdart/
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  universal_html: 
  universal_io: 
