name: exifdart
version: 0.5.0+2
author: Peter Siroki <psiroki@users.noreply.github.com>
description: Decode Exif data from jpeg files (Dart port based on https://github.com/exif-js/exif-js/)
homepage: https://www.github.com/psiroki/exifdart/
environment:
  sdk: '>=1.16.0-dev.5.0 <2.0.0'
