name: exifdart
version: 0.6.0+1
author: Peter Siroki <psiroki@users.noreply.github.com>
description: Decode Exif data from jpeg files (Dart port based on https://github.com/exif-js/exif-js/)
homepage: https://www.github.com/psiroki/exifdart/
environment:
  sdk: '>=2.0.0 <3.0.0'
